export const myProjects = [
  // {
  //   title: "BloodMoon Landing Page",
  //   description:
  //     "An immersive landing page with a scenic mountain landscape, a drifting boat, and a glowing moon. As you scroll, the moon enlarges, revealing the title 'Bloodmoon,' while the boat gracefully glides to the right, eventually disappearing behind the mountains.",
  //   category: ["htmlCss"],
  //   github: "github1",
  //   demo: "demo1",
  //   img: "https://i.ibb.co/2qjGwWy/1.png",
  //   show_more: false,
  //   // colors: [
  //   //   { name: "black", value: "#000000" },
  //   //   { name: "gray", value: "#333333" },
  //   //   { name: "white", value: "#FFFFFF" },
  //   // ],
  //   darkmode_mockups: ["", "", ""],
  //   light_mode_mockups: ["", "", ""],
  // },
  {
    title: "Edu-Candy",
    description:
      "A clean and responsive HTML, CSS, and JavaScript template for an educational platform. Designed to showcase video-based courses across various skills, making learning accessible and engaging for all users",
    category: ["htmlCss", "js"],
    github: "https://github.com/Anwarrior01/edu-candy",
    demo: "https://celadon-fenglisu-526c7a.netlify.app",
    img: "https://i.ibb.co/179CkGq/1.png",
    show_more: true,
    colors: [
      { name: "Violet Blue", value: "#224BCF" },
      { name: "Rose", value: "#FA1D86" },
      { name: "White", value: "#FFFFFF" },
      { name: "Space cadet", value: "#302851" },
      { name: "Gold", value: "#DDB42F" },
      { name: "Black", value: "#000000" },
      { name: "Emerald", value: "#06CC6E" },
    ],
    darkmode_mockups: [
      "https://i.ibb.co/6ZQ3MdW/54-Mockup.png",
      "https://i.ibb.co/zbrSvwc/18-Mockup.png",
      "https://i.ibb.co/n0xP0HK/1-Mobdile.png",
      "https://i.ibb.co/QMFxD95/47-Modbile.png",
    ],
    light_mode_mockups: [
      "https://i.ibb.co/mq5x2pW/54-Mo-Dckup.png",
      "https://i.ibb.co/h9v6LbG/18-Mo-Dckup.png",
      "https://i.ibb.co/mqQ9pRX/1-Mobile.png",
      "https://i.ibb.co/HBhdMv9/47-Mobile.png",
    ],
  },
  {
    title: "DarkMode Calculator",
    description:
      "A versatile HTML, CSS, and JavaScript calculator featuring both dark and light modes for comfortable use in any environment.",
    category: ["htmlCss", "js"],
    github: "https://github.com/Anwarrior01/Darkmode-Lightmode-Calculator",
    demo: "https://unique-flan-4a6709.netlify.app",
    img: "https://i.ibb.co/NYwPJhD/1.png",
    show_more: false,
    // colors: [
    //   { name: "black", value: "#000000" },
    //   { name: "gray", value: "#333333" },
    //   { name: "white", value: "#FFFFFF" },
    // ],
    darkmode_mockups: ["", "", ""],
    light_mode_mockups: ["", "", ""],
  },
  {
    title: "Inventory Management System",
    description:
      "An Inventory Management System built with HTML, CSS, and JavaScript, allowing users to easily add and manage product details including title, category, quantity, price, and additional expenses like marketing and taxes.",
    category: ["js"],
    github: "https://nimble-alfajores-9e0bc0.netlify.app",
    demo: "https://github.com/Anwarrior01/storage-management-webapp",
    img: "https://i.ibb.co/GJKmwZD/Capture.png",
    show_more: false,
    // colors: [
    //   { name: "black", value: "#000000" },
    //   { name: "gray", value: "#333333" },
    //   { name: "white", value: "#FFFFFF" },
    // ],
    darkmode_mockups: ["", "", ""],
    light_mode_mockups: ["", "", ""],
  },
  {
    title: "Modern Design TodoList",
    description:
      "A sleek and modern TodoList application built with HTML, CSS, and JavaScript, allowing users to efficiently manage tasks with an intuitive interface",
    category: ["htmlCss", "js"],
    github: "https://github.com/Anwarrior01/ModernUI-TodoList",
    demo: "https://sweet-sprite-6ade2c.netlify.app",
    img: "https://i.ibb.co/zm7G2rF/1.png",
    show_more: true,
    colors: [
      { name: "Naples Yellow", value: "#ffdc6c" },
      { name: "Atomic Tangerine", value: "#ffac80" },
      { name: "Burnt Sienna", value: "#fea080" },
      { name: "White", value: "#ffffff" },
    ],
    darkmode_mockups: ["https://i.ibb.co/VC3GCfB/43-Mo-Dckup.png", "", ""],
    light_mode_mockups: ["https://i.ibb.co/DDP7W2r/Rectangle-12.png", "", ""],
  },
  {
    title: "Watch Store Landing Page",
    description:
      "A stylish and professional landing page for a watch store, created with HTML and CSS, featuring product showcases and a seamless user experience to attract potential customers",
    category: ["htmlCss"],
    github: "https://github.com/Anwarrior01/watchz",
    demo: "https://resplendent-kitsune-318aa6.netlify.app",
    img: "https://i.ibb.co/NjD7bNX/Capture.png",
    show_more: false,
    // colors: [
    //   { name: "black", value: "#000000" },
    //   { name: "gray", value: "#333333" },
    //   { name: "white", value: "#FFFFFF" },
    // ],
    darkmode_mockups: ["", "", ""],
    light_mode_mockups: ["", "", ""],
  },
  {
    title: "Traveling Agency Landing Page",
    description:
      "A responsive and visually appealing HTML and CSS template for a traveling agency landing page, designed to showcase travel packages and services with engaging imagery and a user-friendly layout.",
    category: ["htmlCss"],
    github: "https://storied-lokum-04af22.netlify.app",
    demo: "https://github.com/Anwarrior01/traveling-agency-webdesign",
    img: "https://i.ibb.co/DKwMmxG/1.png",
    show_more: true,
    colors: [
      { name: "Rich Black", value: "#131C27" },
      { name: "Davy's gray", value: "#555555" },
      { name: "Platinum", value: "#E7E7E7" },
      { name: "343C44", value: "#343C44" },
      { name: "True Blue", value: "#4C6E97" },
      { name: "Lapis Lazuli", value: "#496A92" },
    ],
    darkmode_mockups: [
      "https://i.ibb.co/MMLZ8XT/54-Moc-Dkup.png",
      "https://i.ibb.co/r0vHgjs/18-Moc-Dkup.png",
      "",
    ],
    light_mode_mockups: [
      "https://i.ibb.co/pfh4WrM/54-Mockup.png",
      "https://i.ibb.co/1rG1b5Z/18-Mockup.png",
      "",
    ],
  },
  {
    title: "Photography Portfolio Landing Page",
    description:
      "A captivating landing page for a photography portfolio, crafted with HTML and CSS to beautifully display photo galleries and highlight the photographer's work in an elegant, minimalist design",
    category: ["htmlCss"],
    github: "https://github.com/Anwarrior01/Foton-webdesign",
    demo: "https://melodious-gecko-3d2137.netlify.app",
    img: "https://i.ibb.co/K7Q36V3/1.png",
    show_more: true,
    colors: [
      { name: "White", value: "#FFFFFF" },
      { name: "Black", value: "#000000" },
      { name: "Davy's Gray", value: "#525252" },
      { name: "Platinum", value: "#DAD7DC" },
      { name: "Silver", value: "#C8BFB8" },
      { name: "Onyx", value: "#414141" },
      { name: "Rose Taupe", value: "#906272" },
    ],
    darkmode_mockups: [
      "https://i.ibb.co/12HgY1G/54-Mockup.png",
      "https://i.ibb.co/ZGqZ0rX/18-Mockup.png",
      "https://i.ibb.co/LvTHgbC/1-Mobile.png",
      "https://i.ibb.co/Cvm1Jqh/47-Mobile.png",
    ],
    light_mode_mockups: [
      "https://i.ibb.co/gFCgr1t/54-Modckup.png",
      "https://i.ibb.co/P5r0pj6/18-Mocdkup.png",
      "https://i.ibb.co/R6kSZyD/1-Mdobile.png",
      "https://i.ibb.co/CKCWC4x/47-Mobdile.png",
    ],
  },
  {
    title: "My Old Portfolio",
    description:
      "A simple yet effective HTML, CSS, and Sass portfolio showcasing my early work. While it served its purpose, I've now transitioned to a new, more modern design that better aligns with current trends.",
    category: ["htmlCss"],
    github: "https://github.com/Anwarrior01/old-portfolio",
    demo: "https://stirring-strudel-1231aa.netlify.app",
    img: "https://i.ibb.co/q7m1SHz/1.png",
    show_more: true,
    colors: [
      { name: "White", value: "#FFFFFF" },
      { name: "Pacific Cyan", value: "#38ACCA" },
      { name: "Mint", value: "#38CFA4" },
      { name: "Jet", value: "#2C2C2C" },
      { name: "Black", value: "#000000" },
      { name: "Midnight Green", value: "#154353" },
    ],
    darkmode_mockups: ["https://i.ibb.co/F75WPwP/9-Mockup.png", "", ""],
    light_mode_mockups: ["https://i.ibb.co/ZhJt995/9-Moc-Dkup.png", "", ""],
  },
  {
    title: "Lazy Dev Agency",
    description:
      "Lazy Dev Agency's website showcases our programming services, offering clients a range of development solutions with a modern, user-friendly design that highlights our expertise and commitment to quality.",
    category: ["htmlCss", "js"],
    github: "https://github.com/Anwarrior01/Lazy-dev-agency-website",
    demo: "https://lazy-dev-six.vercel.app",
    img: "https://i.ibb.co/5k6Fj5Q/1.png",
    show_more: true,
    colors: [
      { name: "Licorice", value: "#130213" },
      { name: "Mustard", value: "#FFD95A" },
      { name: "White", value: "#FFFFFF" },
      { name: "Onyx", value: "#454249" },
      { name: "Silver", value: "#A9A9AA" },
      { name: "Maize", value: "#FFE76D" },
      { name: "Xanthous", value: "#E8B32D" },
      { name: "Rich Black", value: "#0B051A" },
      { name: "Black", value: "#010101" },
      { name: "Anti-flash White", value: "#ECECEE" },
    ],
    darkmode_mockups: [
      "https://i.ibb.co/7jkXN5n/43-Mockup.png",
      "https://i.ibb.co/FVdrBXV/1-Mockup.png",
      "https://i.ibb.co/cvXGB8M/9-Mobdile.png",
      "https://i.ibb.co/zXLrN5m/10-Mobidle.png",
    ],
    light_mode_mockups: [
      "https://i.ibb.co/J7htR9g/43-Mocdkup.png",
      "https://i.ibb.co/tztwcj7/1-Mockdup.png",
      "https://i.ibb.co/10M0bYZ/9-Mobile.png",
      "https://i.ibb.co/9nJdFdh/10-Mobile.png",
    ],
  },
  {
    title: "Islami Website",
    description:
      "An Islami website offering global prayer times, a complete Quran for reading, and a collection of the Prophet’s hadiths, providing a comprehensive resource for users seeking Islamic knowledge",
    category: ["htmlCss", "react"],
    github: "https://github.com/Anwarrior01/Islam--",
    demo: "islam-i.vercel.app",
    img: "https://i.ibb.co/bdMSmnB/3.png",
    show_more: true,
    colors: [
      { name: "Rich Black", value: "#060810" },
      { name: "Alice Blue", value: "#E6F0FF" },
      { name: "White", value: "#FFFFFF" },
      { name: "Ivory", value: "#FEFDF2" },
      { name: "Davy's Gray", value: "#4A4A4A" },
      { name: "Lemon Chiffon", value: "#FFF8C7" },
      { name: "Cornsilk", value: "#FCF7D4" },
      { name: "Light Yellow", value: "##fcf8d5" },
      { name: "Beige", value: "#f6f3d4" },
      { name: "Night", value: "#0F1014" },
      { name: "Russian Violet", value: "#201943" },
      { name: "Violet Black", value: "#030418" },
      { name: "Rich Violet black", value: "#0d0a1b" },
    ],
    darkmode_mockups: [
      "https://i.ibb.co/BrgfnsG/43-Mockup.png",
      "https://i.ibb.co/y4x4MRW/1-Mockup.png",
      "https://i.ibb.co/Fm9mZvg/11-Mobile.png",
      "https://i.ibb.co/7gygXg6/10-Mobile.png",
    ],
    light_mode_mockups: [
      "https://i.ibb.co/LRHF8Xq/43-Mocdkup.png",
      "https://i.ibb.co/YBk80nR/1-Mocdkup.png",
      "https://i.ibb.co/YLbWGvn/11-Mobdile.png",
      "https://i.ibb.co/gFtjtQ4/10-Mobdile.png",
    ],
  },
  {
    title: "Javascript Photo Editor",
    description:
      "A JavaScript-powered Photo Editor that allows users to upload images and adjust properties like contrast, brightness, hue, and saturation, providing a simple yet powerful editing experience.",
    category: ["htmlCss", "js"],
    github: "https://github.com/Anwarrior01/javascript-photoEditor",
    demo: "https://endearing-klepon-d2270a.netlify.app",
    img: "https://i.ibb.co/DpVcR2b/Capture.png",
    show_more: true,
    colors: [
      { name: "Eerie black", value: "#222222" },
      { name: "Jet", value: "#333333" },
      { name: "Green Yellow", value: "#ACFF31" },
    ],
    darkmode_mockups: ["https://i.ibb.co/ykZDNmv/43-Mockup.png", "", ""],
    light_mode_mockups: ["https://i.ibb.co/wKLS3nR/43-Mock-Dup.png", "", ""],
  },
];
