export const myProjects = [
  {
    title: "BloodMoon Landing Page",
    description: "Description1",
    category: ["htmlCss"],
    github: "github1",
    demo: "demo1",
    img: "https://i.ibb.co/2qjGwWy/1.png",
  },
  {
    title: "Edu-Candy",
    description: "Description2",
    category: ["htmlCss", "js"],
    github: "github2",
    demo: "demo2",
    img: "https://i.ibb.co/179CkGq/1.png",
  },
  {
    title: "DarkMode Calculator",
    description: "Description3",
    category: ["htmlCss", "js"],
    github: "github3",
    demo: "demo3",
    img: "https://i.ibb.co/NYwPJhD/1.png",
  },
  {
    title: "Inventory Management System",
    description: "Description4",
    category: ["js"],
    github: "github4",
    demo: "demo4",
    img: "https://i.ibb.co/GJKmwZD/Capture.png",
  },
  {
    title: "Modern Design TodoList",
    description: "Description5",
    category: ["htmlCss", "js"],
    github: "github5",
    demo: "demo5",
    img: "https://i.ibb.co/zm7G2rF/1.png",
  },
  {
    title: "Watch Store Landing Page",
    description: "Description6",
    category: ["htmlCss"],
    github: "github6",
    demo: "demo6",
    img: "https://i.ibb.co/NjD7bNX/Capture.png",
  },
  {
    title: "Traveling Agency Landing Page",
    description: "Description7",
    category: ["htmlCss"],
    github: "github7",
    demo: "demo7",
    img: "https://i.ibb.co/DKwMmxG/1.png",
  },
  {
    title: "Photography Porfolion Landing Page",
    description: "Description8",
    category: ["htmlCss"],
    github: "github8",
    demo: "demo8",
    img: "https://i.ibb.co/K7Q36V3/1.png",
  },
  {
    title: "My Old Portfolio",
    description: "Description9",
    category: ["htmlCss"],
    github: "github9",
    demo: "demo9",
    img: "https://i.ibb.co/q7m1SHz/1.png",
  },
  {
    title: "Lazy Dev Agency",
    description: "Description10",
    category: ["htmlCss", "js"],
    github: "github10",
    demo: "demo10",
    img: "https://i.ibb.co/5k6Fj5Q/1.png",
  },
  {
    title: "Islami Website",
    description: "Description11",
    category: ["htmlCss", "react"],
    github: "github11",
    demo: "demo11",
    img: "https://i.ibb.co/bdMSmnB/3.png",
  },
  {
    title: "Javascript Photo Editor",
    description: "Description12",
    category: ["htmlCss", "js"],
    github: "github12",
    demo: "demo12",
    img: "https://i.ibb.co/DpVcR2b/Capture.png",
  },
];
